# Configuración general
spring.application.name=Alumnos
server.port=${PORT:8080}

# Configuración para desarrollo (MySQL)
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:mysql://localhost:3309/alumnos_tec}
spring.datasource.username=${JDBC_DATABASE_USERNAME:root}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:}

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect.storage_engine=innodb

# Configuración específica para PostgreSQL en producción
spring.jpa.properties.hibernate.dialect.postgresql=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Configuración de archivos estáticos (para Vue.js)
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**