spring.application.name=Alumnos

spring.datasource.url=jdbc:mysql://localhost:3309/alumnos_tec
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true